comments: #多说账户申请
    provider: duoshuo
    duoshuo:
        short_name: xxxx
title: 网站标题
safe: false #不要动
highlighter: pygments #不要动
redirects: yes #不要动
site_domain: 设置域名
author: 作者名称
#monokai manni rrt perldoc borland colorful default murphy vs trac fruity native
code_type: manni

page_limit: 10 #设置索引页
#设置变量时候，不要ｔａｂ，一定要空格
indexs: 
 - site: 首页
   url: index.html 
 - site: 编程
   url: tech.html
   tag: tech
 - site: 生活
   url: life.html
   tag: life
 - site: 关于me
   url: resume.html

#404页面配置
page_404:
 refresh_time:7
 btns:
   - info: btn上的名称
     url: 跳转链接


#简历页面
resume:
 Desc:
   - info: "介绍信息"
Jobs: #设置介绍网站链接
   - type: Github
     name: xxx
     url: https://github.com/xx
   - type: Weibo
     name: xxx
     url: http://weibo.com/xx