comments: 
    provider: duoshuo
    duoshuo:
        short_name: intohole
title: 布衣客
safe: false
highlighter: pygments
redirects: yes
site_domain: http://www.buyiker.com
author: IntoHole
#monokai manni rrt perldoc borland colorful default murphy vs trac fruity native
code_type: manni
#index.html 每个ｔａｇ展现的链接数目
page_limit: 10
#设置变量时候，不要ｔａｂ，一定要空格
indexs:
 - site: 首页
   url: index.html
 - site: 机器学习
   url: ml.html
   tag: ml
 - site: 自然语言
   url: nlp.html
   tag: nlp
 - site: 编程
   url: tech.html
   tag: tech
 - site: 开发语言
   url: language.html
   tag: lan
 - site: 前端开发   
   url: frontend.html
   tag: web 
 - site: 生活
   url: life.html
   tag: life
 - site: 关于me
   url: resume.html
page_404:
 refresh_time: 7
 btns:
   - info: 看看我的Github
     url: https://github.com/intohole
   - info: 看看首页
     url: /index.html

resume:
 Desc:
   - info: "Java python shell c and etc... "
   - info: "Mail：aihai2800 AT 126 Dot com"

 Jobs:
   - 
     type: Github
     name: intohole
     url: https://github.com/intohole
   - 
     type: Weibo
     name: 看似大男人的小男人
     url: http://weibo.com/1152049780 
